routes/web.php
<?php
/**
 * @see \Illuminate\Routing\Router
 */

Auth::routes();

Route::middleware('auth')->prefix('admin')->group(function () {
    Route::get('{slug1?}/{slug2?}/{slug3?}/{slug4?}/{slug5?}/{slug6?}', function (...$arg) {
        return view('layouts.ng-back-end');
    });
});



//Illuminate\Routing\PendingResourceRegistration::name(),
Route::resource('post', 'Front\PostController', [
    'only' => [
        'show'
    ],
    'parameters' => [
        'post' => 'post_slug'
    ]
]);

Route::resource('category', 'Front\CategoryController', [
    'only' => [
        'index', 'show'
    ],
    'parameters' => [
        'category' => 'category_slug'
    ]
]);

Route::resource('tag', 'Front\TagController', [
    'only' => [
        'show'
    ],
    'parameters' => [
        'post' => 'tag_slug'
    ]
]);

Route::resource('{page_slug}', 'Front\PageController', [
    'only' => [
        'index'
    ]
]);

Route::get('/', 'HomeController@index')->name('home');

app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Model\Post;
use App\Model\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Категория
 * Class CategoryController
 * @package App\Http\Controllers\Front
 */
class CategoryController extends Controller
{
    /**
     * @param Request $request
     * @param Category $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request, Category $post)
    {
        return view('front.categories', [
            'categories' => Category::paginate(15)
        ]);
    }

    /**
     * @param Request $request
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request, Category $category)
    {
        return view('front.category', [
            'category'  => $category,
            'posts'     => Post::where('status', 1)->orderBy('created_at', 'DESC')->where('category_id', $category->id)->paginate(15)
        ]);
    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Model\Page;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Страница
 * Class PageController
 * @package App\Http\Controllers\Front
 */
class PageController extends Controller
{
    public function index(Request $request, Page $page)
    {
        if(!$page->exists || !$page->status)
        {
            abort(404, '404 Page Not Found');
        }

        return view('front.page', [
            'page' => $page
        ]);
    }
}

app/Http/Controllers/Front/PostController.php
<?php

namespace App\Http\Controllers\Front;

use App\Model\Post;
use Illuminate\Http\Request;
use App\Events\Front\PostHitsEvent;
use App\Http\Controllers\Controller;

/**
 * Пост
 * Class PostController
 * @package App\Http\Controllers\Front
 */
class PostController extends Controller
{
    public function show(Request $request, Post $post)
    {
        if(!$post->exists || !$post->status)
        {
            abort(404, '404 Page Not Found');
        }

        event(new PostHitsEvent($post));

        return view('front.post', [
            'post' => $post
        ]);
    }
}

app/Http/Controllers/Front/TagController.php
<?php

namespace App\Http\Controllers\Front;

use App\Model\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Тег
 * Class TagController
 * @package App\Http\Controllers\Front
 */
class TagController extends Controller
{
    public function show(Request $request, Tag $tag)
    {
        if(!$tag->exists)
        {
            abort(404, '404 Page Not Found');
        }

        $posts = $tag->posts()->orderBy('created_at', 'DESC')->paginate($request->get('perPage', 15));

        return view('front.tag', [
            'tag'   => $tag,
            'posts' => $posts
        ]);
    }
}

resources/views/front/categories.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <nav class="w-100 ml-3 mr-3 breadcrumb">
                <a class="breadcrumb-item" href="/">Home</a>
                <span class="breadcrumb-item active">Categories</span>
            </nav>

            @foreach ($categories as $category)
                <div class="w-25 mb-2">
                <div class="card ml-1 mr-1 h-100">
                    <a href="/category/{{ $category->slug }}">
                        <img class="card-img-top" src="{{$category->image}}" alt="{{$category->name}}">
                    </a>
                    <div class="card-body text-left">
                        <h4 class="card-title">
                            <a href="/category/{{$category->slug}}" class="text-muted">
                                {{str_limit($category->name, 50)}}
                            </a>
                        </h4>
                        <p class="card-text">{{str_limit($category->short_desc, 255)}}</p>
                    </div>
                </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="container">
        {{ $categories->links() }}
    </div>
@endsection

resources/views/front/category.blade.php
@extends('layouts.app')

@include('front.block.meta.title', ['meta_title' => $category->meta_title])
@include('front.block.meta.description', ['meta_description' => $category->meta_description])
@include('front.block.meta.keyword', ['meta_keyword' => $category->meta_keyword])

@section('content')
    <div class="container">
        <h1 class="display-4">{{$category->name}}</h1>
        <nav class="breadcrumb">
            <a class="breadcrumb-item" href="/">Home</a>
            <a class="breadcrumb-item" href="/category">Categories</a>
            <span class="breadcrumb-item active">{{str_limit($category->name, 50)}}</span>
        </nav>
        <div class="list-group">
            @foreach ($posts as $post)
                <a href="/post/{{ $post->slug }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="row">
                        <div class="col-3">
                            <img src="{{$post->image}}" class="rounded float-left" width="100%" alt="...">
                        </div>
                        <div class="col-9">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{$post->name}}</h5>
                                <small>{{date('d.m.Y', strtotime($post->created_at))}}</small>
                            </div>
                            <p class="mb-1">{{str_limit($post->short_desc, random_int(200, 300))}}</p>
                            <small>Donec id elit non mi porta.</small>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
        {{ $posts->links() }}
    </div>
@endsection

resources/views/front/page.blade.php
@extends('layouts.app')

@section('title', $page->meta_title)

@section('content')
    <article class="container">
        <h1 class="display-4">{{$page->name}}</h1>
        <nav class="breadcrumb">
            <a class="breadcrumb-item" href="/">Home</a>
            <span class="breadcrumb-item active">{{str_limit($page->name, 50)}}</span>
        </nav>
        <div class="row">
            <div class="article">
                {!! $page->content !!}
            </div>
        </div>
    </article>
@endsection

resources/views/front/post.blade.php
@extends('layouts.app')

@include('front.block.meta.title', ['meta_title' => $post->meta_title])
@include('front.block.meta.description', ['meta_description' => $post->meta_description])
@include('front.block.meta.keyword', ['meta_keyword' => $post->meta_keyword])
@include('front.block.meta.robots', ['meta_robots' => $post->meta_robots])

@section('content')
    <article class="container">
        <h1 class="display-4">{{$post->name}}</h1>
        <div class="row">
            <div class="col-9">
                <nav class="breadcrumb">
                    <a class="breadcrumb-item" href="/">Home</a>
                    <a class="breadcrumb-item" href="/category">Categories</a>
                    @if($post->category)
                    <a class="breadcrumb-item" href="{{route('category.show', ['category_slug' => $post->category->slug], false)}}">{{str_limit($post->category->name, 50)}}</a>
                    @endif
                    <span class="breadcrumb-item active">{{str_limit($post->name, 50)}}</span>
                </nav>
                <div class="article">
                    <div class="tags">
                        @if($post->tags)
                            @foreach ($post->tags as $tag)
                                <a href="/tag/{{$tag->slug}}" class="badge badge-primary">{{$tag->name}}</a>
                            @endforeach
                        @endif
                    </div>
                    <div class="tags">
                        <i class="fa fa-eye" aria-hidden="true"></i> {{$post->hits or 0}}
                    </div>
                    {!! $post->content !!}
                </div>
            </div>
            <div class="col-3">
                @widget('new-posts', ['category_id' => $post->category_id])
            </div>
        </div>
    </article>
@endsection

resources/views/front/tag.blade.php
@extends('layouts.app')

@section('title', $tag->name)

@section('content')
    <div class="container">
        <h1 class="display-4">Тег - <small class="text-muted">{{$tag->name}}</small></h1>
        <nav class="breadcrumb">
            <a class="breadcrumb-item" href="/">Home</a>
            <span class="breadcrumb-item active">{{$tag->name}}</span>
        </nav>
        <div class="list-group">
            @foreach ($posts as $post)
                <a href="/post/{{ $post->slug }}" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="row">
                        <div class="col-3">
                            <img src="{{$post->image}}" class="rounded float-left" width="100%" alt="...">
                        </div>
                        <div class="col-9">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{$post->name}}</h5>
                                <small>{{date('d.m.Y', strtotime($post->created_at))}}</small>
                            </div>
                            <p class="mb-1">{{str_limit($post->short_desc, random_int(200, 300))}}</p>
                            <small>Donec id elit non mi porta.</small>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </div>
    <div class="container">
        {{ $posts->links() }}
    </div>
@endsection